default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: future_development

test:
  <<: *default
  database: future_test

production:
  <<: *default
  database: future_production
  username: future
  password:
