default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: futuro_platform_development

test:
  <<: *default
  database: futuro_platform_test

production:
  <<: *default
  database: futuro_platform_production
  username: futuro
  password: <%= ENV['FUTURO_DATABASE_PASSWORD'] %>
